function displacement = analytical_solution_annulus_displacement(r,t,theta)
%ANALYTICAL_SOLUTION_ANNULUS_DISPLACEMENT
%    DISPLACEMENT = ANALYTICAL_SOLUTION_ANNULUS_DISPLACEMENT(R,T,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    15-Apr-2021 01:42:12

displacement = cos(theta.*4.0).*cos(t.*1.106470948850117e+1).*besselj(4,r.*1.106470948850117e+1);
